version: "3.7"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app --workers=4 --capture-output --log-level debug --access-logfile '-' --error-logfile '-'
    restart: always
    ports:
     - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
  worker:
    build:
      context: ./app
    hostname: tasks
    entrypoint: celery
    command: -A celery_app.celery worker -l info -E
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"